In [45]:
import pandas as pd
import requests
import json
import numpy as np

In [46]:
url = "https://restcountries.com/v3.1/all"
response=requests.get(url)

In [6]:
if response.status_code == 200:
    data_json = response.json()
else:
    print('Erro ao acessar a API')

In [47]:
df = pd.DataFrame(data_json)

In [48]:
df.head(3)

,name,tld,cca2,ccn3,cca3,independent,status,unMember,currencies,idd,capital,altSpellings,region,languages,translations,latlng,landlocked,area,demonyms,flag,maps,population,car,timezones,continents,flags,coatOfArms,startOfWeek,capitalInfo,cioc,subregion,fifa,borders,gini,postalCode
0,"{'common': 'South Georgia', 'official': 'South...",[.gs],GS,239,SGS,False,officially-assigned,False,"{'SHP': {'name': 'Saint Helena pound', 'symbol...","{'root': '+5', 'suffixes': ['00']}",[King Edward Point],"[GS, South Georgia and the South Sandwich Isla...",Antarctic,{'eng': 'English'},{'ara': {'official': 'Ø¬ÙˆØ±Ø¬ÙŠØ§ Ø§Ù„Ø¬Ù†ÙˆØ¨ÙŠØ© ÙˆØ¬Ø²Ø± Ø³Ø§Ù†...,"[-54.5, -37.0]",False,3903.0,{'eng': {'f': 'South Georgian South Sandwich I...,ðŸ‡¬ðŸ‡¸,{'googleMaps': 'https://goo.gl/maps/mJzdaBwKBb...,30,"{'signs': [''], 'side': 'right'}",[UTC-02:00],[Antarctica],"{'png': 'https://flagcdn.com/w320/gs.png', 'sv...",{},monday,"{'latlng': [-54.28, -36.5]}",NaN,NaN,NaN,NaN,NaN,NaN
1,"{'common': 'Grenada', 'official': 'Grenada', '...",[.gd],GD,308,GRD,True,officially-assigned,True,"{'XCD': {'name': 'Eastern Caribbean dollar', '...","{'root': '+1', 'suffixes': ['473']}",[St. George's],[GD],Americas,{'eng': 'English'},"{'ara': {'official': 'ØºØ±ÙŠÙ†Ø§Ø¯Ø§', 'common': 'ØºØ±ÙŠ...","[12.11666666, -61.66666666]",False,344.0,"{'eng': {'f': 'Grenadian', 'm': 'Grenadian'}, ...",ðŸ‡¬ðŸ‡©,{'googleMaps': 'https://goo.gl/maps/rqWyfUAt4x...,112519,"{'signs': ['WG'], 'side': 'left'}",[UTC-04:00],[North America],"{'png': 'https://flagcdn.com/w320/gd.png', 'sv...",{'png': 'https://mainfacts.com/media/images/co...,monday,"{'latlng': [32.38, -64.68]}",GRN,Caribbean,GRN,NaN,NaN,NaN
2,"{'common': 'Switzerland', 'official': 'Swiss C...",[.ch],CH,756,CHE,True,officially-assigned,True,"{'CHF': {'name': 'Swiss franc', 'symbol': 'Fr.'}}","{'root': '+4', 'suffixes': ['1']}",[Bern],"[CH, Swiss Confederation, Schweiz, Suisse, Svi...",Europe,"{'fra': 'French', 'gsw': 'Swiss German', 'ita'...","{'ara': {'official': 'Ø§Ù„Ø§ØªØ­Ø§Ø¯ Ø§Ù„Ø³ÙˆÙŠØ³Ø±ÙŠ', 'comm...","[47.0, 8.0]",True,41284.0,"{'eng': {'f': 'Swiss', 'm': 'Swiss'}, 'fra': {...",ðŸ‡¨ðŸ‡­,{'googleMaps': 'https://goo.gl/maps/uVuZcXaxSx...,8654622,"{'signs': ['CH'], 'side': 'right'}",[UTC+01:00],[Europe],"{'png': 'https://flagcdn.com/w320/ch.png', 'sv...",{'png': 'https://mainfacts.com/media/images/co...,monday,"{'latlng': [46.92, 7.47]}",SUI,Western Europe,SUI,"[AUT, FRA, ITA, LIE, DEU]",{'2018': 33.1},"{'format': '####', 'regex': '^(\d{4})$'}"

In [49]:
df.describe()

               area    population
count  2.500000e+02  2.500000e+02
mean   6.005848e+05  3.111089e+07
std    1.909805e+06  1.296673e+08
min    4.400000e-01  0.000000e+00
25%    1.194250e+03  2.210995e+05
50%    6.492950e+04  4.912244e+06
75%    3.727260e+05  1.902577e+07
max    1.709824e+07  1.402112e+09

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 35 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          250 non-null    object
 1   tld           249 non-null    object
 2   cca2          250 non-null    object
 3   ccn3          249 non-null    object
 4   cca3          250 non-null    object
 5   independent   249 non-null    object
 6   status        250 non-null    object
 7   unMember      250 non-null    bool
 8   currencies    247 non-null    object
 9   idd           250 non-null    object
 10  capital       246 non-null    object
 11  altSpellings  250 non-null    object
 12  region        250 non-null    object
 13  languages     249 non-null    object
 14  translations  250 non-null    object
 15  latlng        250 non-null    object
 16  landlocked    250 non-null    bool
 17  area          250 non-null    float64
 18  demonyms      249 non-null    object
 19  flag          250 non-null    object
 20  maps          250 non-null    object
 21  population    250 non-null    int64
 22  car           250 non-null    object
 23  timezones     250 non-null    object
 24  continents    250 non-null    object
 25  flags         250 non-null    object
 26  coatOfArms    250 non-null    object
 27  startOfWeek   250 non-null    object
 28  capitalInfo   250 non-null    object
 29  cioc          206 non-null    object
 30  subregion     245 non-null    object
 31  fifa          206 non-null    object
 32  borders       165 non-null    object
 33  gini          167 non-null    object
 34  postalCode    149 non-null    object
dtypes: bool(2), float64(1), int64(1), object(31)
memory usage: 65.1+ KB

In [64]:
data = [
    {
        "name": {"common": "South Georgia", "official": "South Georgia and the South Sandwich Islands"},
        "region": None,
        "population": None
    },
    {
        "name": {"common": "Grenada", "official": "Grenada"},
        "region": "Caribbean",
        "population": 112519
    },
    {
        "name": {"common": "Switzerland", "official": "Swiss Confederation"},
        "region": "Western Europe",
        "population": 8654622
    }
]

In [53]:
nome = [pais['name']['common'] for pais in data]

In [24]:
regiao = [pais.get('region', 'Desconhecida') for pais in data]

In [25]:
populacao = [pais.get('population', 'Desconhecida') for pais in data]

In [54]:
paises = pd.DataFrame({
    "Nome": nome,
    "RegiÃ£o": regiao,
    "PopulaÃ§Ã£o": populacao
})

In [65]:
paises.head(3)

            Nome          RegiÃ£o  PopulaÃ§Ã£o
0  South Georgia            None        NaN
1        Grenada       Caribbean   112519.0
2    Switzerland  Western Europe  8654622.0